services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=56776589gl
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always